
export const ACCOUNT_TYPES = [
  { value: "checking", label: "Checking Account" },
  { value: "savings", label: "Savings Account" },
  { value: "moneyMarket", label: "Money Market Account" },
  { value: "cd", label: "Certificate of Deposit (CD)" },
  { value: "ira", label: "Individual Retirement Account (IRA)" },
  { value: "401k", label: "401(k) Retirement Account" },
  { value: "brokerage", label: "Brokerage Account" },
  { value: "custodial", label: "Custodial Account" },
  { value: "escrow", label: "Escrow Account" },
  { value: "business", label: "Business Account" },
  { value: "commercial", label: "Commercial Account" },
  { value: "creditLine", label: "Credit Line" },
  { value: "mortgage", label: "Mortgage Account" },
  { value: "loan", label: "Loan Account" },
  { value: "trustAccount", label: "Trust Account" },
  { value: "privateEquity", label: "Private Equity Account" },
  { value: "hedge", label: "Hedge Fund Account" },
  { value: "realEstate", label: "Real Estate Investment Account" },
  { value: "commodities", label: "Commodities Account" },
  { value: "derivatives", label: "Derivatives Account" },
  { value: "crypto", label: "Cryptocurrency Account" },
  { value: "fixedIncome", label: "Fixed Income Account" },
  { value: "other", label: "Other" }
];
