
// Financial data aggregators constants
export const AGGREGATORS = [
  "Addepar",
  "Allvue",
  "Allianz Global Investors",
  "Altvia Solutions",
  "Amundi",
  "Archway (SEI)",
  "AssetMetrix",
  "Backstop Solutions",
  "Bipsync",
  "Black Diamond",
  "BlackRock Aladdin",
  "Bloomberg",
  "BNY Mellon Data Aggregation",
  "BNY Mellon Data & Analytics Solutions",
  "Broadridge Financial Solutions",
  "Canoe Intelligence",
  "Capital Group",
  "Charles River Development",
  "Clearwater Analytics",
  "Confluence Technologies",
  "CRUX Asset Management",
  "Delio",
  "Delphi Technology",
  "DiligenceVault",
  "Dynamo Software",
  "EDM Council",
  "Elysys",
  "EquityEffect",
  "Eze Castle",
  "FactSet",
  "FastTrack Investor",
  "Fi-Tek",
  "Finastra",
  "Financial Technologies & Management",
  "Finartis",
  "Fiserv",
  "FIS",
  "Fundata",
  "FundCount",
  "Fundapps",
  "GlobalData",
  "Glue42",
  "HWM Group",
  "IDS GmbH - Data Management",
  "Indata",
  "Ipreo by IHS Markit",
  "Institutional Shareholder Services",
  "Integrated Portfolio Solutions",
  "IntelliFlo",
  "InvestCloud",
  "Investment Metrics",
  "iTech Solutions",
  "IQ-EQ",
  "JTC Group",
  "Kurtosys",
  "Ledgex",
  "Linedata",
  "Liquidnet",
  "Macrobond Financial",
  "Masttro",
  "Merge Technologies",
  "Mirador Financial",
  "MoneyGuidePro",
  "Morningstar",
  "MSCI",
  "MyBlockchain",
  "Northern Trust",
  "Novus",
  "NTT Data",
  "Objectway",
  "Onyx Wealth",
  "OpenPaas",
  "Orion Advisor Solutions",
  "PCR",
  "Pershing",
  "Preqin",
  "PrimeKey",
  "Quantifi",
  "Refinitiv",
  "Riskalyze",
  "S&P Global Market Intelligence",
  "Sage Intacct",
  "Schwab Advisor Center",
  "Sentry Advisors",
  "SimCorp",
  "SmartKYC",
  "Solovis",
  "SS&C Advent",
  "SS&C Black Diamond",
  "SS&C Geneva",
  "SS&C Technologies",
  "State Street Alpha",
  "StatPro Revolution",
  "Tamarac",
  "Temenos",
  "Ter.so",
  "Tikehau Capital",
  "UBS Platform Solutions",
  "ValueScope",
  "Vanguard",
  "Veritas Technologies",
  "Wealthfront",
  "Weal.ai",
  "WideOrbit",
  "Workday",
  "Xignite",
  "Yardi",
  "Other"
];
