
export const CURRENCIES = [
  { value: "USD", label: "US Dollar (USD)" },
  { value: "EUR", label: "Euro (EUR)" },
  { value: "GBP", label: "British Pound (GBP)" },
  { value: "CHF", label: "Swiss Franc (CHF)" },
  { value: "JPY", label: "Japanese Yen (JPY)" },
  { value: "CAD", label: "Canadian Dollar (CAD)" },
  { value: "AUD", label: "Australian Dollar (AUD)" },
  { value: "CNY", label: "Chinese Yuan (CNY)" },
  { value: "HKD", label: "Hong Kong Dollar (HKD)" },
  { value: "SGD", label: "Singapore Dollar (SGD)" },
  { value: "SEK", label: "Swedish Krona (SEK)" },
  { value: "NOK", label: "Norwegian Krone (NOK)" },
  { value: "DKK", label: "Danish Krone (DKK)" },
  { value: "PLN", label: "Polish Złoty (PLN)" },
  { value: "CZK", label: "Czech Koruna (CZK)" },
  { value: "HUF", label: "Hungarian Forint (HUF)" },
  { value: "RON", label: "Romanian Leu (RON)" },
  { value: "BGN", label: "Bulgarian Lev (BGN)" },
  { value: "TRY", label: "Turkish Lira (TRY)" },
  { value: "ILS", label: "Israeli Shekel (ILS)" },
  { value: "ZAR", label: "South African Rand (ZAR)" },
  { value: "BRL", label: "Brazilian Real (BRL)" },
  { value: "MXN", label: "Mexican Peso (MXN)" },
  { value: "ARS", label: "Argentine Peso (ARS)" },
  { value: "CLP", label: "Chilean Peso (CLP)" },
  { value: "COP", label: "Colombian Peso (COP)" },
  { value: "PEN", label: "Peruvian Sol (PEN)" },
  { value: "INR", label: "Indian Rupee (INR)" },
  { value: "IDR", label: "Indonesian Rupiah (IDR)" },
  { value: "MYR", label: "Malaysian Ringgit (MYR)" },
  { value: "PHP", label: "Philippine Peso (PHP)" },
  { value: "THB", label: "Thai Baht (THB)" },
  { value: "KRW", label: "South Korean Won (KRW)" },
  { value: "NZD", label: "New Zealand Dollar (NZD)" },
  { value: "RUB", label: "Russian Ruble (RUB)" },
  { value: "SAR", label: "Saudi Riyal (SAR)" },
  { value: "AED", label: "UAE Dirham (AED)" },
  { value: "QAR", label: "Qatari Riyal (QAR)" },
  { value: "KWD", label: "Kuwaiti Dinar (KWD)" },
  { value: "BHD", label: "Bahraini Dinar (BHD)" }
];
