
// Financial institutions constants
export const INSTITUTIONS = [
  "Agricultural Bank of China",
  "Allianz",
  "American Express",
  "ANZ Bank",
  "Aon",
  "Assicurazioni Generali",
  "AXA",
  "Bank Mandiri",
  "Bank of America",
  "Bank of China",
  "Bank of Communications",
  "Bank of Montreal",
  "Bank of New York Mellon",
  "Banco Bilbao Vizcaya Argentaria (BBVA)",
  "Banco Bradesco",
  "Banco do Brasil",
  "Banco Santander",
  "Barclays",
  "BlackRock",
  "BNP Paribas",
  "Brown Brothers Harriman",
  "Capital One",
  "Charles Schwab",
  "China Construction Bank",
  "China Life Insurance",
  "China Merchants Bank",
  "CIMB Bank",
  "Citigroup",
  "Commerzbank",
  "Commonwealth Bank",
  "Crédit Agricole",
  "Credit Suisse",
  "DBS Bank",
  "Deutsche Bank",
  "Everbright Bank",
  "Fannie Mae",
  "Fidelity Investments",
  "Fifth Third Bank",
  "First Abu Dhabi Bank",
  "First Republic Bank",
  "Franklin Templeton",
  "Goldman Sachs",
  "Grupo Financiero Banorte",
  "Groupe BPCE",
  "Hang Seng Bank",
  "HDFC Bank",
  "HSBC",
  "ICBC",
  "ING Group",
  "Invesco",
  "Intesa Sanpaolo",
  "Itaú Unibanco",
  "JP Morgan Chase",
  "Julius Baer",
  "KB Financial Group",
  "KBC Bank",
  "LGT Bank",
  "Liberty Mutual",
  "Lloyds Banking Group",
  "Macquarie Group",
  "Marsh & McLennan",
  "Mastercard",
  "MetLife",
  "Mitsubishi UFJ Financial Group",
  "Mizuho Financial Group",
  "Morgan Stanley",
  "National Australia Bank",
  "Nationwide Building Society",
  "NatWest Group",
  "Nomura Holdings",
  "Nordea",
  "Northern Trust",
  "Oversea-Chinese Banking Corporation",
  "Ping An Insurance",
  "PNC Financial Services",
  "Postal Savings Bank of China",
  "Prudential Financial",
  "Qatar National Bank",
  "Rabobank",
  "Raymond James",
  "Regions Financial",
  "Rothschild & Co",
  "Royal Bank of Canada",
  "Scotiabank",
  "Shanghai Pudong Development Bank",
  "Shinhan Financial Group",
  "Société Générale",
  "Standard Chartered",
  "State Bank of India",
  "State Street",
  "Sumitomo Mitsui Financial Group",
  "Suncorp Group",
  "Svenska Handelsbanken",
  "TD Bank Group",
  "TD Securities",
  "Truist Financial",
  "UBS",
  "UniCredit",
  "US Bancorp",
  "Vanguard Group",
  "Visa",
  "Wells Fargo",
  "Westpac",
  "Zurich Insurance Group"
];
