
// Top 100 Global Financial Institutions
export const INSTITUTIONS = [
  "Agricultural Bank of China",
  "Allianz",
  "American Express",
  "ANZ Banking Group",
  "Aon",
  "Assicurazioni Generali",
  "AXA",
  "Bank Mandiri",
  "Bank of America",
  "Bank of China",
  "Bank of Communications",
  "Bank of Montreal",
  "Bank of New York Mellon",
  "Banco Bilbao Vizcaya Argentaria (BBVA)",
  "Banco Bradesco",
  "Banco do Brasil",
  "Banco Santander",
  "Barclays",
  "BB&T",
  "BBVA",
  "BlackRock",
  "BNP Paribas",
  "Brown Brothers Harriman",
  "Capital One",
  "Charles Schwab",
  "China Construction Bank",
  "China Life Insurance",
  "China Merchants Bank",
  "CIMB Bank",
  "Citigroup",
  "Commerzbank",
  "Commonwealth Bank",
  "Crédit Agricole",
  "Credit Agricole Group",
  "Credit Suisse",
  "DBS Bank",
  "Deutsche Bank",
  "Everbright Bank",
  "Fannie Mae",
  "Fidelity Investments",
  "Fifth Third Bank",
  "First Abu Dhabi Bank",
  "First Republic Bank",
  "Franklin Templeton",
  "Goldman Sachs",
  "Grupo Financiero Banorte",
  "Groupe BPCE",
  "Hang Seng Bank",
  "HDFC Bank",
  "HSBC Holdings",
  "Industrial and Commercial Bank of China",
  "ING Group",
  "Intesa Sanpaolo",
  "Invesco",
  "Itaú Unibanco",
  "Japan Post Bank",
  "JP Morgan Chase",
  "Julius Baer",
  "KB Financial Group",
  "KBC Bank",
  "KeyCorp",
  "LGT Bank",
  "Liberty Mutual",
  "Lloyds Banking Group",
  "M&T Bank",
  "Macquarie Group",
  "Marsh & McLennan",
  "Mastercard",
  "MetLife",
  "Mitsubishi UFJ Financial Group",
  "Mizuho Financial Group",
  "Morgan Stanley",
  "National Australia Bank",
  "Nationwide Building Society",
  "NatWest Group",
  "Nomura Holdings",
  "Nordea",
  "Northern Trust",
  "Oversea-Chinese Banking Corporation",
  "Ping An Insurance",
  "PNC Financial Services",
  "Postal Savings Bank of China",
  "Prudential Financial",
  "Qatar National Bank",
  "Rabobank",
  "Raymond James",
  "Regions Financial",
  "Rothschild & Co",
  "Royal Bank of Canada",
  "Royal Bank of Scotland",
  "Scotiabank",
  "Shanghai Pudong Development Bank",
  "Shinhan Financial Group",
  "Société Générale",
  "Societe Generale",
  "Standard Chartered",
  "State Bank of India",
  "State Street Corporation",
  "Sumitomo Mitsui Financial Group",
  "Suncorp Group",
  "SunTrust Banks",
  "Svenska Handelsbanken",
  "TD Bank Group",
  "TD Securities",
  "Toronto-Dominion Bank",
  "Truist Financial",
  "UBS Group",
  "UniCredit",
  "US Bancorp",
  "Vanguard Group",
  "Visa",
  "Wells Fargo",
  "Westpac Banking",
  "Zurich Insurance Group",
  "Other (Manual Entry)"
];

// Export a subset of institutions for components that need a smaller list
export const TOP_INSTITUTIONS = [
  "JP Morgan Chase",
  "Goldman Sachs",
  "Morgan Stanley",
  "Bank of America",
  "Wells Fargo",
  "Citigroup",
  "UBS Group",
  "Credit Suisse",
  "HSBC Holdings",
  "BNP Paribas",
  "Deutsche Bank",
  "Barclays",
  "State Street Corporation",
  "Bank of New York Mellon",
  "Northern Trust",
  "BlackRock",
  "Vanguard Group",
  "Fidelity Investments",
  "Charles Schwab",
  "Other (Manual Entry)"
];
