
// Legal entities for institutions (mapping)
export const LEGAL_ENTITIES: Record<string, string[]> = {
  "JP Morgan Chase": [
    "JPMORGAN CHASE BANK, N.A. NEW YORK",
    "JP MORGAN SECURITIES LLC",
    "J.P. MORGAN SECURITIES PLC",
    "JPMORGAN ASSET MANAGEMENT (UK) LIMITED"
  ],
  "Goldman Sachs": [
    "GOLDMAN SACHS BANK USA",
    "GOLDMAN SACHS & CO. LLC",
    "GOLDMAN SACHS INTERNATIONAL",
    "GOLDMAN SACHS ASSET MANAGEMENT, L.P."
  ],
  "Morgan Stanley": [
    "MORGAN STANLEY BANK, N.A.",
    "MORGAN STANLEY & CO. LLC",
    "MORGAN STANLEY SMITH BARNEY LLC",
    "MORGAN STANLEY INVESTMENT MANAGEMENT INC."
  ],
  "Bank of America": [
    "BANK OF AMERICA, N.A.",
    "MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED",
    "BofA SECURITIES, INC.",
    "BANK OF AMERICA EUROPE DESIGNATED ACTIVITY COMPANY"
  ],
  "Wells Fargo": [
    "WELLS FARGO BANK, N.A.",
    "WELLS FARGO SECURITIES, LLC",
    "WELLS FARGO CLEARING SERVICES, LLC",
    "WELLS FARGO FUNDS MANAGEMENT, LLC"
  ],
  "Citigroup": [
    "CITIBANK, N.A.",
    "CITIGROUP GLOBAL MARKETS INC.",
    "CITIGROUP GLOBAL MARKETS LIMITED",
    "CITIGROUP GLOBAL MARKETS EUROPE AG"
  ],
  "UBS Group": [
    "UBS AG",
    "UBS FINANCIAL SERVICES INC.",
    "UBS SECURITIES LLC",
    "UBS ASSET MANAGEMENT (AMERICAS) INC."
  ],
  "Credit Suisse": [
    "CREDIT SUISSE AG",
    "CREDIT SUISSE SECURITIES (USA) LLC",
    "CREDIT SUISSE INTERNATIONAL",
    "CREDIT SUISSE ASSET MANAGEMENT, LLC"
  ],
  "HSBC Holdings": [
    "HSBC BANK PLC",
    "HSBC SECURITIES (USA) INC.",
    "HSBC BANK USA, N.A.",
    "HSBC GLOBAL ASSET MANAGEMENT LIMITED"
  ],
  "BNP Paribas": [
    "BNP PARIBAS",
    "BNP PARIBAS SECURITIES CORP.",
    "BNP PARIBAS ASSET MANAGEMENT FRANCE",
    "BNP PARIBAS S.A."
  ],
  "Deutsche Bank": [
    "DEUTSCHE BANK AG",
    "DEUTSCHE BANK SECURITIES INC.",
    "DEUTSCHE BANK TRUST COMPANY AMERICAS",
    "DWS INVESTMENT GMBH"
  ],
  "Barclays": [
    "BARCLAYS BANK PLC",
    "BARCLAYS CAPITAL INC.",
    "BARCLAYS CAPITAL SECURITIES LIMITED",
    "BARCLAYS INVESTMENT SOLUTIONS LIMITED"
  ],
  "State Street Corporation": [
    "STATE STREET BANK AND TRUST COMPANY",
    "STATE STREET GLOBAL ADVISORS LIMITED",
    "STATE STREET GLOBAL ADVISORS TRUST COMPANY",
    "STATE STREET BANK INTERNATIONAL GMBH"
  ],
  "Bank of New York Mellon": [
    "THE BANK OF NEW YORK MELLON",
    "BNY MELLON CAPITAL MARKETS, LLC",
    "BNY MELLON INVESTMENT MANAGEMENT",
    "THE BANK OF NEW YORK MELLON SA/NV"
  ]
};

// Legal Entity Identifier mapping
export const LEI_MAPPING: Record<string, string> = {
  "JPMORGAN CHASE BANK, N.A. NEW YORK": "7H6GLXDRUGQFU57RNE97",
  "JP MORGAN SECURITIES LLC": "ZBUT11V806EZRVTWT807",
  "J.P. MORGAN SECURITIES PLC": "K6Q0W1PS1L1O4IQL9C32",
  "GOLDMAN SACHS BANK USA": "KD3XUN7C6T14HNAYLU76",
  "GOLDMAN SACHS & CO. LLC": "FOR8UP27PHTHYVLBNG30",
  "GOLDMAN SACHS INTERNATIONAL": "W22LROWP2IHZNBB6K528",
  "MORGAN STANLEY BANK, N.A.": "IGJSJL3JD5P30I6NJZ34",
  "MORGAN STANLEY & CO. LLC": "9R7GPTSO7KV3UQJZQ078",
  "MORGAN STANLEY SMITH BARNEY LLC": "9ZSB5FLPO3FTM154YP34",
  "BANK OF AMERICA, N.A.": "B4TYDEB6GKMZO031MB27",
  "MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED": "8NAV47T0Y26Q178XCGN7",
  "WELLS FARGO BANK, N.A.": "PBLD0EJDB5FWOLXP3B76",
  "CITIBANK, N.A.": "E57ODZWZ7FF32TWEFA76",
  "UBS AG": "BFM8T61CT2L1QCEMIK50",
  "CREDIT SUISSE AG": "ANGGYXNX0JLX3X63JN86",
  "HSBC BANK PLC": "MP6I5ZYZBEU3UXPYFY54",
  "BNP PARIBAS": "R0MUWSFPU8MPRO8K5P83",
  "DEUTSCHE BANK AG": "7LTWFZYICNSX8D621K86",
  "BARCLAYS BANK PLC": "G5GSEF7VJP5I7OUK5573",
  "STATE STREET BANK AND TRUST COMPANY": "571474TGEMMWANRLN572",
  "THE BANK OF NEW YORK MELLON": "HPFHU0OQ28E4N0NFVK49"
};
