
declare module 'lucide-react' {
  import { ComponentType, SVGAttributes } from 'react'

  export interface LucideProps extends SVGAttributes<SVGElement> {
    color?: string
    size?: string | number
    strokeWidth?: string | number
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = ComponentType<LucideProps>

  // Export all available icons from Lucide React
  export const Activity: LucideIcon
  export const ActivitySquare: LucideIcon
  export const AirVent: LucideIcon
  export const Airplay: LucideIcon
  export const AlarmCheck: LucideIcon
  export const AlarmClock: LucideIcon
  export const AlarmClockOff: LucideIcon
  export const AlarmMinus: LucideIcon
  export const AlarmPlus: LucideIcon
  export const Album: LucideIcon
  export const AlertCircle: LucideIcon
  export const AlertOctagon: LucideIcon
  export const AlertTriangle: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignCenterHorizontal: LucideIcon
  export const AlignCenterVertical: LucideIcon
  export const AlignEndHorizontal: LucideIcon
  export const AlignEndVertical: LucideIcon
  export const AlignHorizontalDistributeCenter: LucideIcon
  export const AlignHorizontalDistributeEnd: LucideIcon
  export const AlignHorizontalDistributeStart: LucideIcon
  export const AlignHorizontalJustifyCenter: LucideIcon
  export const AlignHorizontalJustifyEnd: LucideIcon
  export const AlignHorizontalJustifyStart: LucideIcon
  export const AlignHorizontalSpaceAround: LucideIcon
  export const AlignHorizontalSpaceBetween: LucideIcon
  export const AlignJustify: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignRight: LucideIcon
  export const AlignStartHorizontal: LucideIcon
  export const AlignStartVertical: LucideIcon
  export const AlignVerticalDistributeCenter: LucideIcon
  export const AlignVerticalDistributeEnd: LucideIcon
  export const AlignVerticalDistributeStart: LucideIcon
  export const AlignVerticalJustifyCenter: LucideIcon
  export const AlignVerticalJustifyEnd: LucideIcon
  export const AlignVerticalJustifyStart: LucideIcon
  export const AlignVerticalSpaceAround: LucideIcon
  export const AlignVerticalSpaceBetween: LucideIcon
  export const Ampersand: LucideIcon
  export const Ampersands: LucideIcon
  export const Anchor: LucideIcon
  export const Angry: LucideIcon
  export const Annoyed: LucideIcon
  export const Antenna: LucideIcon
  export const Aperture: LucideIcon
  export const AppWindow: LucideIcon
  export const Apple: LucideIcon
  export const Archive: LucideIcon
  export const ArchiveRestore: LucideIcon
  export const ArchiveX: LucideIcon
  export const AreaChart: LucideIcon
  export const Armchair: LucideIcon
  export const ArrowBigDown: LucideIcon
  export const ArrowBigDownDash: LucideIcon
  export const ArrowBigLeft: LucideIcon
  export const ArrowBigLeftDash: LucideIcon
  export const ArrowBigRight: LucideIcon
  export const ArrowBigRightDash: LucideIcon
  export const ArrowBigUp: LucideIcon
  export const ArrowBigUpDash: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowDown01: LucideIcon
  export const ArrowDown10: LucideIcon
  export const ArrowDownAZ: LucideIcon
  export const ArrowDownCircle: LucideIcon
  export const ArrowDownFromLine: LucideIcon
  export const ArrowDownLeft: LucideIcon
  export const ArrowDownLeftFromCircle: LucideIcon
  export const ArrowDownLeftSquare: LucideIcon
  export const ArrowDownNarrowWide: LucideIcon
  export const ArrowDownRight: LucideIcon
  export const ArrowDownRightFromCircle: LucideIcon
  export const ArrowDownRightSquare: LucideIcon
  export const ArrowDownSquare: LucideIcon
  export const ArrowDownToDot: LucideIcon
  export const ArrowDownToLine: LucideIcon
  export const ArrowDownUp: LucideIcon
  export const ArrowDownWideNarrow: LucideIcon
  export const ArrowDownZA: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowLeftCircle: LucideIcon
  export const ArrowLeftFromLine: LucideIcon
  export const ArrowLeftRight: LucideIcon
  export const ArrowLeftSquare: LucideIcon
  export const ArrowLeftToLine: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowRightCircle: LucideIcon
  export const ArrowRightFromLine: LucideIcon
  export const ArrowRightLeft: LucideIcon
  export const ArrowRightSquare: LucideIcon
  export const ArrowRightToLine: LucideIcon
  export const ArrowUp: LucideIcon
  export const ArrowUp01: LucideIcon
  export const ArrowUp10: LucideIcon
  export const ArrowUpAZ: LucideIcon
  export const ArrowUpCircle: LucideIcon
  export const ArrowUpDown: LucideIcon
  export const ArrowUpFromDot: LucideIcon
  export const ArrowUpFromLine: LucideIcon
  export const ArrowUpLeft: LucideIcon
  export const ArrowUpLeftFromCircle: LucideIcon
  export const ArrowUpLeftSquare: LucideIcon
  export const ArrowUpNarrowWide: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const ArrowUpRightFromCircle: LucideIcon
  export const ArrowUpRightSquare: LucideIcon
  export const ArrowUpSquare: LucideIcon
  export const ArrowUpToLine: LucideIcon
  export const ArrowUpWideNarrow: LucideIcon
  export const ArrowUpZA: LucideIcon
  export const ArrowsUpFromLine: LucideIcon
  export const Asterisk: LucideIcon
  export const AtSign: LucideIcon
  export const Atom: LucideIcon
  export const Award: LucideIcon
  export const Axe: LucideIcon
  export const Axis3D: LucideIcon
  export const Baby: LucideIcon
  export const Backpack: LucideIcon
  export const Badge: LucideIcon
  export const BadgeAlert: LucideIcon
  export const BadgeCent: LucideIcon
  export const BadgeCheck: LucideIcon
  export const BadgeDollarSign: LucideIcon
  export const BadgeEuro: LucideIcon
  export const BadgeHelp: LucideIcon
  export const BadgeInfo: LucideIcon
  export const BadgeJapaneseYen: LucideIcon
  export const BadgeMinus: LucideIcon
  export const BadgePercent: LucideIcon
  export const BadgePlus: LucideIcon
  export const BadgePoundSterling: LucideIcon
  export const BadgeRussianRuble: LucideIcon
  export const BadgeSwissFranc: LucideIcon
  export const BadgeX: LucideIcon
  export const BaggageClaim: LucideIcon
  export const Ban: LucideIcon
  export const Banana: LucideIcon
  export const Banknote: LucideIcon
  export const BarChart: LucideIcon
  export const BarChart2: LucideIcon
  export const BarChart3: LucideIcon
  export const BarChart4: LucideIcon
  export const BarChartBig: LucideIcon
  export const BarChartHorizontal: LucideIcon
  export const Baseline: LucideIcon
  export const Bath: LucideIcon
  export const Battery: LucideIcon
  export const BatteryCharging: LucideIcon
  export const BatteryFull: LucideIcon
  export const BatteryLow: LucideIcon
  export const BatteryMedium: LucideIcon
  export const BatteryWarning: LucideIcon
  export const Beaker: LucideIcon
  export const Bean: LucideIcon
  export const BeanOff: LucideIcon
  export const Bed: LucideIcon
  export const BedDouble: LucideIcon
  export const BedSingle: LucideIcon
  export const Beef: LucideIcon
  export const Beer: LucideIcon
  export const Bell: LucideIcon
  export const BellDot: LucideIcon
  export const BellMinus: LucideIcon
  export const BellOff: LucideIcon
  export const BellPlus: LucideIcon
  export const BellRing: LucideIcon
  export const Bike: LucideIcon
  export const Binary: LucideIcon
  export const Biohazard: LucideIcon
  export const Bird: LucideIcon
  export const Bitcoin: LucideIcon
  export const Blinds: LucideIcon
  export const Bluetooth: LucideIcon
  export const BluetoothConnected: LucideIcon
  export const BluetoothOff: LucideIcon
  export const BluetoothSearching: LucideIcon
  export const Bold: LucideIcon
  export const Bomb: LucideIcon
  export const Bone: LucideIcon
  export const Book: LucideIcon
  export const BookA: LucideIcon
  export const BookAudio: LucideIcon
  export const BookCheck: LucideIcon
  export const BookCopy: LucideIcon
  export const BookDown: LucideIcon
  export const BookKey: LucideIcon
  export const BookLock: LucideIcon
  export const BookMarked: LucideIcon
  export const BookMinus: LucideIcon
  export const BookOpen: LucideIcon
  export const BookOpenCheck: LucideIcon
  export const BookPlus: LucideIcon
  export const BookTemplate: LucideIcon
  export const BookUp: LucideIcon
  export const BookX: LucideIcon
  export const Bookmark: LucideIcon
  export const BookmarkCheck: LucideIcon
  export const BookmarkMinus: LucideIcon
  export const BookmarkPlus: LucideIcon
  export const BookmarkX: LucideIcon
  export const Bot: LucideIcon
  export const Box: LucideIcon
  export const BoxSelect: LucideIcon
  export const Boxes: LucideIcon
  export const Braces: LucideIcon
  export const Brackets: LucideIcon
  export const Brain: LucideIcon
  export const BrainCircuit: LucideIcon
  export const BrainCog: LucideIcon
  export const Briefcase: LucideIcon
  export const Brush: LucideIcon
  export const Bug: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Bus: LucideIcon
  export const Cake: LucideIcon
  export const Calculator: LucideIcon
  export const Calendar: LucideIcon
  export const CalendarCheck: LucideIcon
  export const CalendarCheck2: LucideIcon
  export const CalendarClock: LucideIcon
  export const CalendarDays: LucideIcon
  export const CalendarHeart: LucideIcon
  export const CalendarMinus: LucideIcon
  export const CalendarOff: LucideIcon
  export const CalendarPlus: LucideIcon
  export const CalendarRange: LucideIcon
  export const CalendarSearch: LucideIcon
  export const CalendarX: LucideIcon
  export const CalendarX2: LucideIcon
  export const Camera: LucideIcon
  export const CameraOff: LucideIcon
  export const Candy: LucideIcon
  export const CandyCane: LucideIcon
  export const CandyOff: LucideIcon
  export const Car: LucideIcon
  export const Carrot: LucideIcon
  export const CaseSensitive: LucideIcon
  export const Cast: LucideIcon
  export const Castle: LucideIcon
  export const Cat: LucideIcon
  export const Check: LucideIcon
  export const CheckCheck: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const CheckSquare: LucideIcon
  export const ChefHat: LucideIcon
  export const Cherry: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronFirst: LucideIcon
  export const ChevronLast: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronsDown: LucideIcon
  export const ChevronsDownUp: LucideIcon
  export const ChevronsLeft: LucideIcon
  export const ChevronsLeftRight: LucideIcon
  export const ChevronsRight: LucideIcon
  export const ChevronsRightLeft: LucideIcon
  export const ChevronsUp: LucideIcon
  export const ChevronsUpDown: LucideIcon
  export const Chrome: LucideIcon
  export const Church: LucideIcon
  export const Cigarette: LucideIcon
  export const CigaretteOff: LucideIcon
  export const Circle: LucideIcon
  export const CircleDashed: LucideIcon
  export const CircleDollarSign: LucideIcon
  export const CircleDot: LucideIcon
  export const CircleDotDashed: LucideIcon
  export const CircleEllipsis: LucideIcon
  export const CircleEqual: LucideIcon
  export const CircleOff: LucideIcon
  export const CircleSlash: LucideIcon
  export const CircleSlash2: LucideIcon
  export const CircuitBoard: LucideIcon
  export const Citrus: LucideIcon
  export const Clapperboard: LucideIcon
  export const Clipboard: LucideIcon
  export const ClipboardCheck: LucideIcon
  export const ClipboardCopy: LucideIcon
  export const ClipboardEdit: LucideIcon
  export const ClipboardList: LucideIcon
  export const ClipboardPaste: LucideIcon
  export const ClipboardSignature: LucideIcon
  export const ClipboardType: LucideIcon
  export const ClipboardX: LucideIcon
  export const Clock: LucideIcon
  export const Clock1: LucideIcon
  export const Clock10: LucideIcon
  export const Clock11: LucideIcon
  export const Clock12: LucideIcon
  export const Clock2: LucideIcon
  export const Clock3: LucideIcon
  export const Clock4: LucideIcon
  export const Clock5: LucideIcon
  export const Clock6: LucideIcon
  export const Clock7: LucideIcon
  export const Clock8: LucideIcon
  export const Clock9: LucideIcon
  export const Cloud: LucideIcon
  export const CloudCog: LucideIcon
  export const CloudDrizzle: LucideIcon
  export const CloudFog: LucideIcon
  export const CloudHail: LucideIcon
  export const CloudLightning: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudMoonRain: LucideIcon
  export const CloudOff: LucideIcon
  export const CloudRain: LucideIcon
  export const CloudRainWind: LucideIcon
  export const CloudSnow: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudSunRain: LucideIcon
  export const Cloudy: LucideIcon
  export const Clover: LucideIcon
  export const Club: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Codepen: LucideIcon
  export const Codesandbox: LucideIcon
  export const Coffee: LucideIcon
  export const Cog: LucideIcon
  export const Coins: LucideIcon
  export const Columns: LucideIcon
  export const Command: LucideIcon
  export const Compass: LucideIcon
  export const Component: LucideIcon
  export const ConciergeBell: LucideIcon
  export const Construction: LucideIcon
  export const Contact: LucideIcon
  export const Contrast: LucideIcon
  export const Cookie: LucideIcon
  export const Copy: LucideIcon
  export const CopyCheck: LucideIcon
  export const CopyMinus: LucideIcon
  export const CopyPlus: LucideIcon
  export const CopySlash: LucideIcon
  export const CopyX: LucideIcon
  export const Copyleft: LucideIcon
  export const Copyright: LucideIcon
  export const CornerDownLeft: LucideIcon
  export const CornerDownRight: LucideIcon
  export const CornerLeftDown: LucideIcon
  export const CornerLeftUp: LucideIcon
  export const CornerRightDown: LucideIcon
  export const CornerRightUp: LucideIcon
  export const CornerUpLeft: LucideIcon
  export const CornerUpRight: LucideIcon
  export const Cpu: LucideIcon
  export const CreativeCommons: LucideIcon
  export const CreditCard: LucideIcon
  export const Croissant: LucideIcon
  export const Crop: LucideIcon
  export const Cross: LucideIcon
  export const Crosshair: LucideIcon
  export const Crown: LucideIcon
  export const CupSoda: LucideIcon
  export const Currency: LucideIcon
  export const Database: LucideIcon
  export const DatabaseBackup: LucideIcon
  export const Delete: LucideIcon
  export const Dessert: LucideIcon
  export const Diamond: LucideIcon
  export const Dice1: LucideIcon
  export const Dice2: LucideIcon
  export const Dice3: LucideIcon
  export const Dice4: LucideIcon
  export const Dice5: LucideIcon
  export const Dice6: LucideIcon
  export const Dices: LucideIcon
  export const Diff: LucideIcon
  export const Disc: LucideIcon
  export const Disc2: LucideIcon
  export const Disc3: LucideIcon
  export const Divide: LucideIcon
  export const DivideCircle: LucideIcon
  export const DivideSquare: LucideIcon
  export const Dna: LucideIcon
  export const DnaOff: LucideIcon
  export const Dog: LucideIcon
  export const DollarSign: LucideIcon
  export const Donut: LucideIcon
  export const DoorClosed: LucideIcon
  export const DoorOpen: LucideIcon
  export const Dot: LucideIcon
  export const Download: LucideIcon
  export const DownloadCloud: LucideIcon
  export const Dribbble: LucideIcon
  export const Droplet: LucideIcon
  export const Droplets: LucideIcon
  export const Drum: LucideIcon
  export const Drumstick: LucideIcon
  export const Dumbbell: LucideIcon
  export const Ear: LucideIcon
  export const EarOff: LucideIcon
  export const Earth: LucideIcon
  export const Egg: LucideIcon
  export const EggFried: LucideIcon
  export const EggOff: LucideIcon
  export const Equal: LucideIcon
  export const EqualNot: LucideIcon
  export const Eraser: LucideIcon
  export const Euro: LucideIcon
  export const Expand: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Facebook: LucideIcon
  export const Factory: LucideIcon
  export const Fan: LucideIcon
  export const FastForward: LucideIcon
  export const Feather: LucideIcon
  export const FerrisWheel: LucideIcon
  export const Figma: LucideIcon
  export const File: LucideIcon
  export const FileArchive: LucideIcon
  export const FileAudio: LucideIcon
  export const FileAudio2: LucideIcon
  export const FileAxis3D: LucideIcon
  export const FileBadge: LucideIcon
  export const FileBadge2: LucideIcon
  export const FileBarChart: LucideIcon
  export const FileBarChart2: LucideIcon
  export const FileBox: LucideIcon
  export const FileCheck: LucideIcon
  export const FileCheck2: LucideIcon
  export const FileClock: LucideIcon
  export const FileCode: LucideIcon
  export const FileCode2: LucideIcon
  export const FileCog: LucideIcon
  export const FileCog2: LucideIcon
  export const FileDiff: LucideIcon
  export const FileDigit: LucideIcon
  export const FileDown: LucideIcon
  export const FileEdit: LucideIcon
  export const FileHeart: LucideIcon
  export const FileImage: LucideIcon
  export const FileInput: LucideIcon
  export const FileJson: LucideIcon
  export const FileJson2: LucideIcon
  export const FileKey: LucideIcon
  export const FileKey2: LucideIcon
  export const FileLock: LucideIcon
  export const FileLock2: LucideIcon
  export const FileMinus: LucideIcon
  export const FileMinus2: LucideIcon
  export const FileOutput: LucideIcon
  export const FilePenLine: LucideIcon
  export const FilePieChart: LucideIcon
  export const FilePlus: LucideIcon
  export const FilePlus2: LucideIcon
  export const FileQuestion: LucideIcon
  export const FileScan: LucideIcon
  export const FileSearch: LucideIcon
  export const FileSearch2: LucideIcon
  export const FileSignature: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileStack: LucideIcon
  export const FileSymlink: LucideIcon
  export const FileTerminal: LucideIcon
  export const FileText: LucideIcon
  export const FileType: LucideIcon
  export const FileType2: LucideIcon
  export const FileUp: LucideIcon
  export const FileVideo: LucideIcon
  export const FileVideo2: LucideIcon
  export const FileVolume: LucideIcon
  export const FileVolume2: LucideIcon
  export const FileWarning: LucideIcon
  export const FileX: LucideIcon
  export const FileX2: LucideIcon
  export const Files: LucideIcon
  export const FilesText: LucideIcon
  export const Film: LucideIcon
  export const Filter: LucideIcon
  export const FilterX: LucideIcon
  export const Fingerprint: LucideIcon
  export const Fish: LucideIcon
  export const FishOff: LucideIcon
  export const Flag: LucideIcon
  export const FlagOff: LucideIcon
  export const FlagTriangleLeft: LucideIcon
  export const FlagTriangleRight: LucideIcon
  export const Flame: LucideIcon
  export const FlameKindling: LucideIcon
  export const Flashlight: LucideIcon
  export const FlashlightOff: LucideIcon
  export const FlaskConical: LucideIcon
  export const FlaskConicalOff: LucideIcon
  export const FlaskRound: LucideIcon
  export const FlipHorizontal: LucideIcon
  export const FlipHorizontal2: LucideIcon
  export const FlipVertical: LucideIcon
  export const FlipVertical2: LucideIcon
  export const Flower: LucideIcon
  export const Flower2: LucideIcon
  export const Focus: LucideIcon
  export const FoldHorizontal: LucideIcon
  export const FoldVertical: LucideIcon
  export const Folder: LucideIcon
  export const FolderArchive: LucideIcon
  export const FolderCheck: LucideIcon
  export const FolderClock: LucideIcon
  export const FolderClosed: LucideIcon
  export const FolderCog: LucideIcon
  export const FolderCog2: LucideIcon
  export const FolderDot: LucideIcon
  export const FolderDown: LucideIcon
  export const FolderGit: LucideIcon
  export const FolderGit2: LucideIcon
  export const FolderHeart: LucideIcon
  export const FolderInput: LucideIcon
  export const FolderKanban: LucideIcon
  export const FolderKey: LucideIcon
  export const FolderLock: LucideIcon
  export const FolderMinus: LucideIcon
  export const FolderOpen: LucideIcon
  export const FolderOpenDot: LucideIcon
  export const FolderOutput: LucideIcon
  export const FolderPlus: LucideIcon
  export const FolderRoot: LucideIcon
  export const FolderSearch: LucideIcon
  export const FolderSearch2: LucideIcon
  export const FolderSync: LucideIcon
  export const FolderTree: LucideIcon
  export const FolderUp: LucideIcon
  export const FolderX: LucideIcon
  export const Folders: LucideIcon
  export const Footprints: LucideIcon
  export const Forklift: LucideIcon
  export const FormInput: LucideIcon
  export const Forward: LucideIcon
  export const Frame: LucideIcon
  export const Framer: LucideIcon
  export const Frown: LucideIcon
  export const Fuel: LucideIcon
  export const FunctionSquare: LucideIcon
  export const Gallery: LucideIcon
  export const GalleryHorizontal: LucideIcon
  export const GalleryHorizontalEnd: LucideIcon
  export const GalleryThumbnails: LucideIcon
  export const GalleryVertical: LucideIcon
  export const GalleryVerticalEnd: LucideIcon
  export const Gamepad: LucideIcon
  export const Gamepad2: LucideIcon
  export const GanttChart: LucideIcon
  export const GanttChartSquare: LucideIcon
  export const Gauge: LucideIcon
  export const GaugeCircle: LucideIcon
  export const Gavel: LucideIcon
  export const Gem: LucideIcon
  export const Ghost: LucideIcon
  export const Gift: LucideIcon
  export const GitBranch: LucideIcon
  export const GitBranchPlus: LucideIcon
  export const GitCommit: LucideIcon
  export const GitCompare: LucideIcon
  export const GitFork: LucideIcon
  export const GitMerge: LucideIcon
  export const GitPullRequest: LucideIcon
  export const GitPullRequestClosed: LucideIcon
  export const GitPullRequestCreateArrow: LucideIcon
  export const GitPullRequestDraft: LucideIcon
  export const Github: LucideIcon
  export const Gitlab: LucideIcon
  export const GlassWater: LucideIcon
  export const Glasses: LucideIcon
  export const Globe: LucideIcon
  export const Globe2: LucideIcon
  export const Goal: LucideIcon
  export const Grab: LucideIcon
  export const GraduationCap: LucideIcon
  export const Grape: LucideIcon
  export const Grid: LucideIcon
  export const Grip: LucideIcon
  export const GripHorizontal: LucideIcon
  export const GripVertical: LucideIcon
  export const Group: LucideIcon
  export const Guitar: LucideIcon
  export const Hammer: LucideIcon
  export const Hand: LucideIcon
  export const HandCoins: LucideIcon
  export const HandHelping: LucideIcon
  export const HandMetal: LucideIcon
  export const HardDrive: LucideIcon
  export const HardDriveDownload: LucideIcon
  export const HardDriveUpload: LucideIcon
  export const HardHat: LucideIcon
  export const Hash: LucideIcon
  export const Haze: LucideIcon
  export const Heading: LucideIcon
  export const Heading1: LucideIcon
  export const Heading2: LucideIcon
  export const Heading3: LucideIcon
  export const Heading4: LucideIcon
  export const Heading5: LucideIcon
  export const Heading6: LucideIcon
  export const Headphones: LucideIcon
  export const Heart: LucideIcon
  export const HeartCrack: LucideIcon
  export const HeartHandshake: LucideIcon
  export const HeartOff: LucideIcon
  export const HeartPulse: LucideIcon
  export const HelpCircle: LucideIcon
  export const HelpingHand: LucideIcon
  export const Hexagon: LucideIcon
  export const Highlighter: LucideIcon
  export const History: LucideIcon
  export const Home: LucideIcon
  export const Hop: LucideIcon
  export const HopOff: LucideIcon
  export const Hotel: LucideIcon
  export const Hourglass: LucideIcon
  export const IceCream: LucideIcon
  export const IceCream2: LucideIcon
  export const Image: LucideIcon
  export const ImageDown: LucideIcon
  export const ImageMinus: LucideIcon
  export const ImageOff: LucideIcon
  export const ImagePlus: LucideIcon
  export const Import: LucideIcon
  export const Inbox: LucideIcon
  export const Indent: LucideIcon
  export const IndianRupee: LucideIcon
  export const Infinity: LucideIcon
  export const Info: LucideIcon
  export const InfoIcon: LucideIcon
  export const Inspect: LucideIcon
  export const Instagram: LucideIcon
  export const Italic: LucideIcon
  export const JapaneseYen: LucideIcon
  export const Joystick: LucideIcon
  export const Key: LucideIcon
  export const KeyRound: LucideIcon
  export const KeySquare: LucideIcon
  export const Keyboard: LucideIcon
  export const Landmark: LucideIcon
  export const Languages: LucideIcon
  export const Laptop: LucideIcon
  export const Laptop2: LucideIcon
  export const Lasso: LucideIcon
  export const LassoSelect: LucideIcon
  export const Laugh: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const LayoutGrid: LucideIcon
  export const LayoutList: LucideIcon
  export const LayoutPanelLeft: LucideIcon
  export const LayoutPanelTop: LucideIcon
  export const LayoutTemplate: LucideIcon
  export const Leaf: LucideIcon
  export const LeafyGreen: LucideIcon
  export const Library: LucideIcon
  export const LifeBuoy: LucideIcon
  export const Lightbulb: LucideIcon
  export const LightbulbIcon: LucideIcon
  export const LightbulbOff: LucideIcon
  export const LineChart: LucideIcon
  export const Link: LucideIcon
  export const Link2: LucideIcon
  export const LinkIcon: LucideIcon
  export const Link2Off: LucideIcon
  export const Linkedin: LucideIcon
  export const List: LucideIcon
  export const ListChecks: LucideIcon
  export const ListEnd: LucideIcon
  export const ListFilter: LucideIcon
  export const ListMinus: LucideIcon
  export const ListMusic: LucideIcon
  export const ListOrdered: LucideIcon
  export const ListPlus: LucideIcon
  export const ListStart: LucideIcon
  export const ListTodo: LucideIcon
  export const ListTree: LucideIcon
  export const ListVideo: LucideIcon
  export const ListX: LucideIcon
  export const Loader: LucideIcon
  export const Loader2: LucideIcon
  export const Locate: LucideIcon
  export const LocateFixed: LucideIcon
  export const LocateOff: LucideIcon
  export const Lock: LucideIcon
  export const LockKeyhole: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const Luggage: LucideIcon
  export const MPlusL: LucideIcon
  export const Magnet: LucideIcon
  export const Mail: LucideIcon
  export const MailCheck: LucideIcon
  export const MailMinus: LucideIcon
  export const MailOpen: LucideIcon
  export const MailPlus: LucideIcon
  export const MailQuestion: LucideIcon
  export const MailSearch: LucideIcon
  export const MailWarning: LucideIcon
  export const MailX: LucideIcon
  export const Mailbox: LucideIcon
  export const Mails: LucideIcon
  export const Map: LucideIcon
  export const MapIcon: LucideIcon
  export const MapPinned: LucideIcon
  export const Maximize: LucideIcon
  export const Maximize2: LucideIcon
  export const Medal: LucideIcon
  export const Megaphone: LucideIcon
  export const MegaphoneOff: LucideIcon
  export const Meh: LucideIcon
  export const Menu: LucideIcon
  export const MenuSquare: LucideIcon
  export const Merge: LucideIcon
  export const MessageCircle: LucideIcon
  export const MessageSquare: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const MessageSquareDot: LucideIcon
  export const MessageSquareMore: LucideIcon
  export const MessageSquareOff: LucideIcon
  export const MessageSquarePlus: LucideIcon
  export const MessageSquareQuote: LucideIcon
  export const MessageSquareReply: LucideIcon
  export const MessageSquareShare: LucideIcon
  export const MessageSquareText: LucideIcon
  export const MessageSquareWarning: LucideIcon
  export const MessageSquareX: LucideIcon
  export const MessagesSquare: LucideIcon
  export const Mic: LucideIcon
  export const Mic2: LucideIcon
  export const MicOff: LucideIcon
  export const Microscope: LucideIcon
  export const Microwave: LucideIcon
  export const Milestone: LucideIcon
  export const Milk: LucideIcon
  export const MilkOff: LucideIcon
  export const Minimize: LucideIcon
  export const Minimize2: LucideIcon
  export const Minus: LucideIcon
  export const MinusCircle: LucideIcon
  export const MinusSquare: LucideIcon
  export const Monitor: LucideIcon
  export const MonitorDown: LucideIcon
  export const MonitorOff: LucideIcon
  export const MonitorSmartphone: LucideIcon
  export const MonitorSpeaker: LucideIcon
  export const MonitorUp: LucideIcon
  export const MoonIcon: LucideIcon
  export const Moon: LucideIcon
  export const MoonStar: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const MoreVertical: LucideIcon
  export const Mountain: LucideIcon
  export const MountainSnow: LucideIcon
  export const Mouse: LucideIcon
  export const MousePointer: LucideIcon
  export const MousePointer2: LucideIcon
  export const MousePointerClick: LucideIcon
  export const Move: LucideIcon
  export const Move3D: LucideIcon
  export const MoveDiagonal: LucideIcon
  export const MoveDiagonal2: LucideIcon
  export const MoveHorizontal: LucideIcon
  export const MoveVertical: LucideIcon
  export const Music: LucideIcon
  export const Music2: LucideIcon
  export const Music3: LucideIcon
  export const Music4: LucideIcon
  export const Navigation: LucideIcon
  export const Navigation2: LucideIcon
  export const Navigation2Off: LucideIcon
  export const NavigationOff: LucideIcon
  export const Network: LucideIcon
  export const Newspaper: LucideIcon
  export const Nfc: LucideIcon
  export const Notebook: LucideIcon
  export const NotebookPen: LucideIcon
  export const NotebookTabs: LucideIcon
  export const Notes: LucideIcon
  export const NotesPen: LucideIcon
  export const NotesPenLine: LucideIcon
  export const NotesPlus: LucideIcon
  export const NotificationOff: LucideIcon
  export const Nut: LucideIcon
  export const NutOff: LucideIcon
  export const Octagon: LucideIcon
  export const OctagonAlert: LucideIcon
  export const OctagonCheck: LucideIcon
  export const OctagonHelp: LucideIcon
  export const OctagonMinus: LucideIcon
  export const OctagonOff: LucideIcon
  export const OctagonPlus: LucideIcon
  export const OctagonX: LucideIcon
  export const Option: LucideIcon
  export const Orbit: LucideIcon
  export const Outdent: LucideIcon
  export const Package: LucideIcon
  export const Package2: LucideIcon
  export const PackageCheck: LucideIcon
  export const PackageMinus: LucideIcon
  export const PackageOpen: LucideIcon
  export const PackagePlus: LucideIcon
  export const PackageSearch: LucideIcon
  export const PackageX: LucideIcon
  export const PaintBucket: LucideIcon
  export const Paintbrush: LucideIcon
  export const Paintbrush2: LucideIcon
  export const Palette: LucideIcon
  export const Palmtree: LucideIcon
  export const PanelBottom: LucideIcon
  export const PanelBottomClose: LucideIcon
  export const PanelBottomInactive: LucideIcon
  export const PanelBottomOpen: LucideIcon
  export const PanelLeft: LucideIcon
  export const PanelLeftClose: LucideIcon
  export const PanelLeftInactive: LucideIcon
  export const PanelLeftOpen: LucideIcon
  export const PanelRight: LucideIcon
  export const PanelRightClose: LucideIcon
  export const PanelRightInactive: LucideIcon
  export const PanelRightOpen: LucideIcon
  export const PanelTop: LucideIcon
  export const PanelTopClose: LucideIcon
  export const PanelTopInactive: LucideIcon
  export const PanelTopOpen: LucideIcon
  export const Paperclip: LucideIcon
  export const Parentheses: LucideIcon
  export const ParkingCircle: LucideIcon
  export const ParkingCircleOff: LucideIcon
  export const ParkingMeter: LucideIcon
  export const ParkingSquare: LucideIcon
  export const ParkingSquareOff: LucideIcon
  export const PartyPopper: LucideIcon
  export const Pause: LucideIcon
  export const PauseCircle: LucideIcon
  export const PauseOctagon: LucideIcon
  export const PawPrint: LucideIcon
  export const Peace: LucideIcon
  export const Pen: LucideIcon
  export const PenLine: LucideIcon
  export const PenSixPointedLine: LucideIcon
  export const PenSixPointedPlus: LucideIcon
  export const PenSquareLine: LucideIcon
  export const PenSquarePlus: LucideIcon
  export const PenTool: LucideIcon
  export const Pencil: LucideIcon
  export const PencilLine: LucideIcon
  export const PencilRuler: LucideIcon
  export const Pentagon: LucideIcon
  export const Percent: LucideIcon
  export const PercentCircle: LucideIcon
  export const PercentDiamond: LucideIcon
  export const PercentSquare: LucideIcon
  export const PersonStanding: LucideIcon
  export const Phone: LucideIcon
  export const PhoneCall: LucideIcon
  export const PhoneForwarded: LucideIcon
  export const PhoneIncoming: LucideIcon
  export const PhoneMissed: LucideIcon
  export const PhoneOff: LucideIcon
  export const PhoneOutgoing: LucideIcon
  export const Pi: LucideIcon
  export const PiSquare: LucideIcon
  export const Piano: LucideIcon
  export const PictureInPicture: LucideIcon
  export const PictureInPicture2: LucideIcon
  export const PieChart: LucideIcon
  export const PiggyBank: LucideIcon
  export const Pilcrow: LucideIcon
  export const PilcrowSquare: LucideIcon
  export const Pill: LucideIcon
  export const Pin: LucideIcon
  export const PinOff: LucideIcon
  export const Pipette: LucideIcon
  export const Pizza: LucideIcon
  export const Plane: LucideIcon
  export const PlaneLanding: LucideIcon
  export const PlaneTakeoff: LucideIcon
  export const Play: LucideIcon
  export const PlayCircle: LucideIcon
  export const PlaySquare: LucideIcon
  export const Plug: LucideIcon
  export const Plug2: LucideIcon
  export const PlugZap: LucideIcon
  export const PlugZap2: LucideIcon
  export const Plus: LucideIcon
  export const PlusCircle: LucideIcon
  export const PlusSquare: LucideIcon
  export const Pocket: LucideIcon
  export const PocketKnife: LucideIcon
  export const Podcast: LucideIcon
  export const Pointer: LucideIcon
  export const Popcorn: LucideIcon
  export const Popsicle: LucideIcon
  export const PoundSterling: LucideIcon
  export const Power: LucideIcon
  export const PowerOff: LucideIcon
  export const PowerSquare: LucideIcon
  export const Presentation: LucideIcon
  export const Printer: LucideIcon
  export const Projector: LucideIcon
  export const Puzzle: LucideIcon
  export const PuzzleIcon: LucideIcon
  export const Pyramid: LucideIcon
  export const QrCode: LucideIcon
  export const Quote: LucideIcon
  export const Rabbit: LucideIcon
  export const Radiation: LucideIcon
  export const RadioReceiver: LucideIcon
  export const RadioTower: LucideIcon
  export const Rainbow: LucideIcon
  export const Rat: LucideIcon
  export const Ratio: LucideIcon
  export const Receipt: LucideIcon
  export const RectangleHorizontal: LucideIcon
  export const RectangleVertical: LucideIcon
  export const Recycle: LucideIcon
  export const Redo: LucideIcon
  export const Redo2: LucideIcon
  export const RefreshCcw: LucideIcon
  export const RefreshCw: LucideIcon
  export const Refrigerator: LucideIcon
  export const Regex: LucideIcon
  export const RemoveFormatting: LucideIcon
  export const Repeat: LucideIcon
  export const Repeat1: LucideIcon
  export const Repeat2: LucideIcon
  export const Replace: LucideIcon
  export const ReplaceAll: LucideIcon
  export const Reply: LucideIcon
  export const ReplyAll: LucideIcon
  export const Rewind: LucideIcon
  export const Ribbon: LucideIcon
  export const Rocket: LucideIcon
  export const RockingChair: LucideIcon
  export const RollerCoaster: LucideIcon
  export const Rotate3D: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const Route: LucideIcon
  export const RouteOff: LucideIcon
  export const Router: LucideIcon
  export const Rows: LucideIcon
  export const Rss: LucideIcon
  export const Ruler: LucideIcon
  export const RussianRuble: LucideIcon
  export const Sailboat: LucideIcon
  export const Salad: LucideIcon
  export const Sandwich: LucideIcon
  export const Satellite: LucideIcon
  export const SatelliteDish: LucideIcon
  export const Save: LucideIcon
  export const SaveAll: LucideIcon
  export const Scale: LucideIcon
  export const Scale3D: LucideIcon
  export const Scaling: LucideIcon
  export const Scan: LucideIcon
  export const ScanFace: LucideIcon
  export const ScanLine: LucideIcon
  export const ScanSearch: LucideIcon
  export const ScanText: LucideIcon
  export const School: LucideIcon
  export const School2: LucideIcon
  export const Scissors: LucideIcon
  export const ScissorsLineDashed: LucideIcon
  export const ScissorsSquare: LucideIcon
  export const ScissorsSquareDashedBottom: LucideIcon
  export const ScreenShare: LucideIcon
  export const ScreenShareOff: LucideIcon
  export const Scroll: LucideIcon
  export const ScrollText: LucideIcon
  export const Search: LucideIcon
  export const SearchCheck: LucideIcon
  export const SearchCode: LucideIcon
  export const SearchSlash: LucideIcon
  export const SearchX: LucideIcon
  export const Send: LucideIcon
  export const SendHorizontal: LucideIcon
  export const SendToBack: LucideIcon
  export const SeparatorHorizontal: LucideIcon
  export const SeparatorVertical: LucideIcon
  export const Server: LucideIcon
  export const ServerCog: LucideIcon
  export const ServerCrash: LucideIcon
  export const ServerOff: LucideIcon
  export const Settings: LucideIcon
  export const Settings2: LucideIcon
  export const Shapes: LucideIcon
  export const Share: LucideIcon
  export const Share2: LucideIcon
  export const Sheet: LucideIcon
  export const Shell: LucideIcon
  export const Shield: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldBan: LucideIcon
  export const ShieldCheck: LucideIcon
  export const ShieldEllipsis: LucideIcon
  export const ShieldHalf: LucideIcon
  export const ShieldMinus: LucideIcon
  export const ShieldOff: LucideIcon
  export const ShieldPlus: LucideIcon
  export const ShieldQuestion: LucideIcon
  export const ShieldX: LucideIcon
  export const Ship: LucideIcon
  export const Shirt: LucideIcon
  export const ShoppingBag: LucideIcon
  export const ShoppingBasket: LucideIcon
  export const ShoppingCart: LucideIcon
  export const Shovel: LucideIcon
  export const ShowerHead: LucideIcon
  export const Shrink: LucideIcon
  export const Shrub: LucideIcon
  export const Shuffle: LucideIcon
  export const Sigma: LucideIcon
  export const SigmaSquare: LucideIcon
  export const Signal: LucideIcon
  export const SignalHigh: LucideIcon
  export const SignalLow: LucideIcon
  export const SignalMedium: LucideIcon
  export const SignalZero: LucideIcon
  export const Siren: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Skull: LucideIcon
  export const Slack: LucideIcon
  export const Slash: LucideIcon
  export const Slice: LucideIcon
  export const Sliders: LucideIcon
  export const SlidersHorizontal: LucideIcon
  export const Smartphone: LucideIcon
  export const SmartphoneCharging: LucideIcon
  export const SmartphoneNfc: LucideIcon
  export const Smile: LucideIcon
  export const SmilePlus: LucideIcon
  export const Snail: LucideIcon
  export const Snowflake: LucideIcon
  export const Sofa: LucideIcon
  export const Soup: LucideIcon
  export const Space: LucideIcon
  export const Spade: LucideIcon
  export const Sparkle: LucideIcon
  export const Sparkles: LucideIcon
  export const Speaker: LucideIcon
  export const SpellCheck: LucideIcon
  export const SpellCheck2: LucideIcon
  export const Spline: LucideIcon
  export const Split: LucideIcon
  export const SplitSquareHorizontal: LucideIcon
  export const SplitSquareVertical: LucideIcon
  export const SprayCan: LucideIcon
  export const Sprout: LucideIcon
  export const Square: LucideIcon
  export const SquareAsterisk: LucideIcon
  export const SquareCheck: LucideIcon
  export const SquareCode: LucideIcon
  export const SquareDashedBottom: LucideIcon
  export const SquareDot: LucideIcon
  export const SquareEqual: LucideIcon
  export const SquareGantt: LucideIcon
  export const SquareKanban: LucideIcon
  export const SquareOff: LucideIcon
  export const SquarePen: LucideIcon
  export const SquareStack: LucideIcon
  export const SquareTerminal: LucideIcon
  export const SquareUser: LucideIcon
  export const SquareUserRound: LucideIcon
  export const Squirrel: LucideIcon
  export const Stamp: LucideIcon
  export const Star: LucideIcon
  export const StarHalf: LucideIcon
  export const StarOff: LucideIcon
  export const StepBack: LucideIcon
  export const StepForward: LucideIcon
  export const Stethoscope: LucideIcon
  export const Sticker: LucideIcon
  export const StickyNote: LucideIcon
  export const StopCircle: LucideIcon
  export const Store: LucideIcon
  export const StretchHorizontal: LucideIcon
  export const StretchVertical: LucideIcon
  export const Strikethrough: LucideIcon
  export const Subscript: LucideIcon
  export const Subtitles: LucideIcon
  export const Sun: LucideIcon
  export const SunDim: LucideIcon
  export const SunIcon: LucideIcon
  export const SunMedium: LucideIcon
  export const SunMoon: LucideIcon
  export const SunSnow: LucideIcon
  export const Sunrise: LucideIcon
  export const Sunset: LucideIcon
  export const Superscript: LucideIcon
  export const SwissFranc: LucideIcon
  export const SwitchCamera: LucideIcon
  export const Sword: LucideIcon
  export const Swords: LucideIcon
  export const Syringe: LucideIcon
  export const Table: LucideIcon
  export const Table2: LucideIcon
  export const Tablet: LucideIcon
  export const TabletSmartphone: LucideIcon
  export const Tablets: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Target: LucideIcon
  export const Tent: LucideIcon
  export const Terminal: LucideIcon
  export const TerminalSquare: LucideIcon
  export const TestTube: LucideIcon
  export const TestTube2: LucideIcon
  export const TestTubes: LucideIcon
  export const Text: LucideIcon
  export const TextCursor: LucideIcon
  export const TextCursorInput: LucideIcon
  export const TextIcon: LucideIcon
  export const TextSearch: LucideIcon
  export const TextSelect: LucideIcon
  export const TextSelection: LucideIcon
  export const Theater: LucideIcon
  export const Thermometer: LucideIcon
  export const ThermometerSnowflake: LucideIcon
  export const ThermometerSun: LucideIcon
  export const ThumbsDown: LucideIcon
  export const ThumbsUp: LucideIcon
  export const Ticket: LucideIcon
  export const Timer: LucideIcon
  export const TimerIcon: LucideIcon
  export const TimerOff: LucideIcon
  export const TimerReset: LucideIcon
  export const ToggleLeft: LucideIcon
  export const ToggleRight: LucideIcon
  export const Tornado: LucideIcon
  export const Torus: LucideIcon
  export const TouchpadOff: LucideIcon
  export const TowerControl: LucideIcon
  export const ToyBrick: LucideIcon
  export const Tractor: LucideIcon
  export const TrafficCone: LucideIcon
  export const Train: LucideIcon
  export const TrainFront: LucideIcon
  export const TrainFrontTunnel: LucideIcon
  export const TrainTrack: LucideIcon
  export const TramFront: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const TreeDeciduous: LucideIcon
  export const TreePine: LucideIcon
  export const Trees: LucideIcon
  export const Trello: LucideIcon
  export const TrendingDown: LucideIcon
  export const TrendingUp: LucideIcon
  export const Triangle: LucideIcon
  export const TriangleAlert: LucideIcon
  export const TriangleRight: LucideIcon
  export const Trophy: LucideIcon
  export const Truck: LucideIcon
  export const Tv: LucideIcon
  export const Tv2: LucideIcon
  export const Twitch: LucideIcon
  export const Twitter: LucideIcon
  export const Type: LucideIcon
  export const TypeIcon: LucideIcon
  export const Umbrella: LucideIcon
  export const UmbrellaOff: LucideIcon
  export const Underline: LucideIcon
  export const Undo: LucideIcon
  export const Undo2: LucideIcon
  export const UndoDot: LucideIcon
  export const UnfoldHorizontal: LucideIcon
  export const UnfoldVertical: LucideIcon
  export const Ungroup: LucideIcon
  export const Unlink: LucideIcon
  export const Unlink2: LucideIcon
  export const Unlock: LucideIcon
  export const Unplug: LucideIcon
  export const Upload: LucideIcon
  export const UploadCloud: LucideIcon
  export const Usb: LucideIcon
  export const User: LucideIcon
  export const UserCheck: LucideIcon
  export const UserCog: LucideIcon
  export const UserMinus: LucideIcon
  export const UserPlus: LucideIcon
  export const UserRound: LucideIcon
  export const UserRoundCheck: LucideIcon
  export const UserRoundCog: LucideIcon
  export const UserRoundMinus: LucideIcon
  export const UserRoundPlus: LucideIcon
  export const UserRoundX: LucideIcon
  export const UserSearch: LucideIcon
  export const UserX: LucideIcon
  export const Users: LucideIcon
  export const UsersRound: LucideIcon
  export const Utensils: LucideIcon
  export const UtensilsCrossed: LucideIcon
  export const UtilityPole: LucideIcon
  export const Variable: LucideIcon
  export const Vault: LucideIcon
  export const Vegan: LucideIcon
  export const VenetianMask: LucideIcon
  export const Vibrate: LucideIcon
  export const VibrateOff: LucideIcon
  export const Video: LucideIcon
  export const VideoOff: LucideIcon
  export const Videotape: LucideIcon
  export const View: LucideIcon
  export const Voicemail: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Vote: LucideIcon
  export const Wallet: LucideIcon
  export const Wallpaper: LucideIcon
  export const Wand: LucideIcon
  export const WandSparkles: LucideIcon
  export const Warehouse: LucideIcon
  export const WashingMachine: LucideIcon
  export const Watch: LucideIcon
  export const Waves: LucideIcon
  export const Webcam: LucideIcon
  export const Webhook: LucideIcon
  export const Weight: LucideIcon
  export const Wheat: LucideIcon
  export const WheatOff: LucideIcon
  export const WholeWord: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const Wind: LucideIcon
  export const Wine: LucideIcon
  export const WineOff: LucideIcon
  export const Workflow: LucideIcon
  export const Wrench: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
  export const XIcon: LucideIcon
  export const XOctagon: LucideIcon
  export const XSquare: LucideIcon
  export const Youtube: LucideIcon
  export const Zap: LucideIcon
  export const ZapIcon: LucideIcon
  export const ZapOff: LucideIcon
  export const ZoomIn: LucideIcon
  export const ZoomOut: LucideIcon

  export const icons: Record<string, LucideIcon>
  export const dynamicIconImports: Record<string, () => Promise<{ default: LucideIcon }>>
  
  export const Icon: ComponentType<{
    name?: string
    color?: string
    size?: string | number
    strokeWidth?: string | number
    absoluteStrokeWidth?: boolean
    iconNode?: any
  }>
}
