
// Top Financial Aggregators
export const AGGREGATORS = [
  "Plaid",
  "Yodlee",
  "Finicity",
  "Tink",
  "Salt Edge",
  "TrueLayer",
  "Akoya",
  "MX",
  "Flinks",
  "Nordic API Gateway",
  "Klarna Kosma",
  "Mono",
  "Belvo",
  "Railsbank",
  "Addepar",
  "Allvue",
  "Backstop Solutions",
  "Black Diamond",
  "Canoe Intelligence",
  "Clearwater Analytics",
  "Dynamo Software",
  "Eze Castle",
  "FactSet",
  "FIS",
  "FundCount",
  "Ledgex",
  "Masttro",
  "Mirador",
  "PCR",
  "Pitchbook",
  "SEI Archway",
  "Solovis",
  "SS&C Advent",
  "SS&C Geneva",
  "Tamarac",
  "Yardi",
  "Other (Manual Entry)"
].sort();
