
// Top Financial Aggregators
export const AGGREGATORS = [
  "Addepar",
  "Allvue",
  "Archway (SEI)",
  "Backstop Solutions",
  "Bipsync",
  "Black Diamond",
  "BlackRock Aladdin",
  "Bloomberg",
  "BNY Mellon Data & Analytics",
  "Broadridge Financial Solutions",
  "Canoe Intelligence",
  "Charles River Development",
  "Clearwater Analytics",
  "Confluence Technologies",
  "Dynamo Software",
  "eFront (BlackRock)",
  "Enfusion",
  "FactSet",
  "Fidelity National Information",
  "Finartis",
  "Finastra",
  "FIS",
  "Fiserv",
  "FundCount",
  "Glue42",
  "Hazeltree",
  "Intercontinental Exchange (ICE)",
  "InvestCloud",
  "iPreo (IHS Markit)",
  "Linedata",
  "Macrobond Financial",
  "Markit EDM",
  "Masttro",
  "Mirador",
  "Morningstar",
  "MSCI",
  "Novus",
  "Orion Advisor Solutions",
  "PCR",
  "Preqin",
  "Refinitiv",
  "S&P Global Market Intelligence",
  "SimCorp",
  "SS&C Advent",
  "SS&C Black Diamond",
  "SS&C Geneva",
  "SS&C Technologies",
  "State Street Alpha",
  "Tamarac",
  "Yardi",
  "Other (Manual Entry)"
].sort();
