
// Jurisdictions
export const JURISDICTIONS = [
  "Andorra", "Australia", "Austria", "Bahamas", "Bahrain", "Barbados", "Belgium", 
  "Bermuda", "British Virgin Islands", "Brunei", "Canada", "Cayman Islands", 
  "China", "Cyprus", "Denmark", "Finland", "France", "Germany", "Gibraltar", 
  "Greece", "Guernsey", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", 
  "Ireland", "Isle of Man", "Israel", "Italy", "Japan", "Jersey", "Kuwait", 
  "Lebanon", "Liechtenstein", "Luxembourg", "Malaysia", "Malta", "Mauritius", 
  "Mexico", "Monaco", "Netherlands", "New Zealand", "Norway", "Panama", "Philippines", 
  "Portugal", "Qatar", "Russia", "Saudi Arabia", "Seychelles", "Singapore", 
  "South Africa", "South Korea", "Spain", "Sweden", "Switzerland", "Taiwan", 
  "Thailand", "Turkey", "UAE", "United Kingdom", "United States", "Vietnam"
];

// Countries
export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", 
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", 
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", 
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", 
  "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", 
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", 
  "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", 
  "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", 
  "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", 
  "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", 
  "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", 
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", 
  "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", 
  "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", 
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", 
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
  "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", 
  "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", 
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", 
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", 
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", 
  "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", 
  "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", 
  "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", 
  "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", 
  "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", 
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", 
  "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", 
  "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", 
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", 
  "Zimbabwe"
];

// US States
export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
  "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
  "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
  "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", 
  "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
  "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", 
  "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", 
  "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
];

// Top 20 Global Currencies
export const CURRENCIES = [
  "USD - US Dollar",
  "EUR - Euro",
  "JPY - Japanese Yen",
  "GBP - British Pound",
  "CHF - Swiss Franc",
  "AUD - Australian Dollar",
  "CAD - Canadian Dollar",
  "CNY - Chinese Yuan",
  "HKD - Hong Kong Dollar",
  "NZD - New Zealand Dollar",
  "SEK - Swedish Krona",
  "KRW - South Korean Won",
  "SGD - Singapore Dollar",
  "NOK - Norwegian Krone",
  "MXN - Mexican Peso",
  "INR - Indian Rupee",
  "BRL - Brazilian Real",
  "ZAR - South African Rand",
  "RUB - Russian Ruble",
  "TRY - Turkish Lira"
];

// Top 100 Global Financial Institutions
export const INSTITUTIONS = [
  "JP Morgan Chase",
  "Industrial and Commercial Bank of China",
  "Bank of America",
  "Wells Fargo",
  "China Construction Bank",
  "HSBC Holdings",
  "Agricultural Bank of China",
  "Citigroup",
  "Bank of China",
  "BNP Paribas",
  "Mitsubishi UFJ Financial Group",
  "Goldman Sachs",
  "Morgan Stanley",
  "Credit Agricole Group",
  "Japan Post Bank",
  "Deutsche Bank",
  "Banco Santander",
  "Bank of Communications",
  "Societe Generale",
  "Mizuho Financial Group",
  "Royal Bank of Canada",
  "Toronto-Dominion Bank",
  "UniCredit",
  "Intesa Sanpaolo",
  "ING Group",
  "Barclays",
  "BBVA",
  "Standard Chartered",
  "Bank of Montreal",
  "Credit Suisse",
  "UBS Group",
  "Royal Bank of Scotland",
  "Nordea",
  "Sumitomo Mitsui Financial Group",
  "Commonwealth Bank",
  "Westpac Banking",
  "National Australia Bank",
  "ANZ Banking Group",
  "Scotiabank",
  "Lloyds Banking Group",
  "US Bancorp",
  "PNC Financial Services",
  "Capital One",
  "Bank of New York Mellon",
  "State Street Corporation",
  "BB&T",
  "SunTrust Banks",
  "Northern Trust",
  "M&T Bank",
  "KeyCorp",
  "Other (Manual Entry)"
];

// Top Financial Aggregators
export const AGGREGATORS = [
  "Plaid",
  "Yodlee",
  "Finicity",
  "Tink",
  "Salt Edge",
  "TrueLayer",
  "Akoya",
  "MX",
  "Flinks",
  "Nordic API Gateway",
  "Klarna Kosma",
  "Mono",
  "Belvo",
  "Railsbank",
  "Other (Manual Entry)"
];
