
// Form options for the onboarding forms

// Legal entity types (sorted alphabetically with "Other" at the end)
export const LEGAL_ENTITY_TYPES = [
  "Corporation",
  "Foundation",
  "Limited Liability Company (LLC)",
  "Limited Partnership (LP)",
  "Non-Profit Organization",
  "Partnership",
  "Private Investment Company (PIC)",
  "Sole Proprietorship",
  "Trust",
  "Other"
];

// Jurisdictions (expanded list, sorted alphabetically)
export const JURISDICTIONS = [
  "Andorra",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Belgium",
  "Belize",
  "Bermuda",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Canada",
  "Cayman Islands",
  "Channel Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Gibraltar",
  "Greece",
  "Grenada",
  "Guernsey",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Kuwait",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Malaysia",
  "Malta",
  "Marshall Islands",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Panama",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "San Marino",
  "Saudi Arabia",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Trinidad and Tobago",
  "Turkey",
  "Turks and Caicos Islands",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vanuatu",
  "Vietnam"
];

// Document types
export const DOCUMENT_TYPES = [
  { value: "incorporation", label: "Certificate of Incorporation" },
  { value: "registration", label: "Business Registration" },
  { value: "taxCertificate", label: "Tax Certificate" },
  { value: "ownership", label: "Ownership Structure" },
  { value: "other", label: "Other Legal Document" }
];

// Identification document types
export const ID_DOCUMENT_TYPES = [
  { value: "passport", label: "Passport" },
  { value: "drivingLicense", label: "Driving License" },
  { value: "nationalId", label: "National ID" }
];

// Countries
export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", 
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", 
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", 
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", 
  "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", 
  "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", 
  "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", 
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", 
  "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", 
  "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", 
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", 
  "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", 
  "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", 
  "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", 
  "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", 
  "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", 
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", 
  "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", 
  "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", 
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", 
  "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", 
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", 
  "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", 
  "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", 
  "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", 
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", 
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
].sort();

// US States
export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
  "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", 
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", 
  "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", 
  "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", 
  "New Hampshire", "New Jersey", "New Mexico", "New York", 
  "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", 
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
  "West Virginia", "Wisconsin", "Wyoming"
].sort();

// Aggregators
export const AGGREGATORS = [
  "Addepar",
  "Allvue",
  "Backstop Solutions",
  "Black Diamond",
  "Canoe Intelligence",
  "Clearwater Analytics",
  "Dynamo Software",
  "Eze Castle",
  "FactSet",
  "FIS",
  "FundCount",
  "Ledgex",
  "Masttro",
  "Mirador",
  "PCR",
  "Pitchbook",
  "SEI Archway",
  "Solovis",
  "SS&C Advent",
  "SS&C Geneva",
  "Tamarac",
  "Yardi"
];

// Also export INSTITUTIONS for ManualEntrySection
export const INSTITUTIONS = [
  "Addepar",
  "Bank of America",
  "Barclays",
  "BlackRock",
  "BNP Paribas",
  "Charles Schwab",
  "Citibank",
  "Credit Suisse",
  "Deutsche Bank",
  "Fidelity",
  "Goldman Sachs",
  "HSBC",
  "J.P. Morgan",
  "Julius Baer",
  "LGT Bank",
  "Morgan Stanley",
  "Northern Trust",
  "Pictet",
  "Raymond James",
  "Rothschild & Co",
  "State Street",
  "TD Ameritrade",
  "UBS",
  "Vanguard",
  "Wells Fargo"
].sort();

// Account types
export const ACCOUNT_TYPES = [
  "Investment",
  "Checking",
  "Savings",
  "Brokerage",
  "Custody",
  "Trust",
  "Retirement",
  "Portfolio",
  "Cash",
  "Margin",
  "Private Equity",
  "Hedge Fund",
  "Venture Capital",
  "Real Estate",
  "Fixed Income",
  "Credit"
];

// Currencies with symbols
export const CURRENCIES = [
  "USD - US Dollar",
  "EUR - Euro",
  "GBP - British Pound",
  "CHF - Swiss Franc",
  "JPY - Japanese Yen",
  "CNY - Chinese Yuan",
  "CAD - Canadian Dollar",
  "AUD - Australian Dollar",
  "HKD - Hong Kong Dollar",
  "SGD - Singapore Dollar",
  "NZD - New Zealand Dollar",
  "SEK - Swedish Krona",
  "NOK - Norwegian Krone",
  "DKK - Danish Krone",
  "BRL - Brazilian Real",
  "INR - Indian Rupee",
  "MXN - Mexican Peso",
  "ZAR - South African Rand"
].sort();
