
// Top 100 Global Financial Institutions
export const INSTITUTIONS = [
  "JP Morgan Chase",
  "Industrial and Commercial Bank of China",
  "Bank of America",
  "Wells Fargo",
  "China Construction Bank",
  "HSBC Holdings",
  "Agricultural Bank of China",
  "Citigroup",
  "Bank of China",
  "BNP Paribas",
  "Mitsubishi UFJ Financial Group",
  "Goldman Sachs",
  "Morgan Stanley",
  "Credit Agricole Group",
  "Japan Post Bank",
  "Deutsche Bank",
  "Banco Santander",
  "Bank of Communications",
  "Societe Generale",
  "Mizuho Financial Group",
  "Royal Bank of Canada",
  "Toronto-Dominion Bank",
  "UniCredit",
  "Intesa Sanpaolo",
  "ING Group",
  "Barclays",
  "BBVA",
  "Standard Chartered",
  "Bank of Montreal",
  "Credit Suisse",
  "UBS Group",
  "Royal Bank of Scotland",
  "Nordea",
  "Sumitomo Mitsui Financial Group",
  "Commonwealth Bank",
  "Westpac Banking",
  "National Australia Bank",
  "ANZ Banking Group",
  "Scotiabank",
  "Lloyds Banking Group",
  "US Bancorp",
  "PNC Financial Services",
  "Capital One",
  "Bank of New York Mellon",
  "State Street Corporation",
  "BB&T",
  "SunTrust Banks",
  "Northern Trust",
  "M&T Bank",
  "KeyCorp",
  "Other (Manual Entry)"
].sort();
