
// Jurisdictions (expanded list, sorted alphabetically)
export const JURISDICTIONS = [
  "Andorra",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Belgium",
  "Belize",
  "Bermuda",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Canada",
  "Cayman Islands",
  "Channel Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Gibraltar",
  "Greece",
  "Grenada",
  "Guernsey",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Kuwait",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Malaysia",
  "Malta",
  "Marshall Islands",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Panama",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "San Marino",
  "Saudi Arabia",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Trinidad and Tobago",
  "Turkey",
  "Turks and Caicos Islands",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vanuatu",
  "Vietnam"
];
