
// Financial data constants

// Institutions - Expanded list of top global financial institutions
export const INSTITUTIONS = [
  "Agricultural Bank of China",
  "Allianz",
  "American Express",
  "ANZ Bank",
  "Aon",
  "Assicurazioni Generali",
  "AXA",
  "Bank Mandiri",
  "Bank of America",
  "Bank of China",
  "Bank of Communications",
  "Bank of Montreal",
  "Bank of New York Mellon",
  "Banco Bilbao Vizcaya Argentaria (BBVA)",
  "Banco Bradesco",
  "Banco do Brasil",
  "Banco Santander",
  "Barclays",
  "BlackRock",
  "BNP Paribas",
  "Brown Brothers Harriman",
  "Capital One",
  "Charles Schwab",
  "China Construction Bank",
  "China Life Insurance",
  "China Merchants Bank",
  "CIMB Bank",
  "Citigroup",
  "Commerzbank",
  "Commonwealth Bank",
  "Crédit Agricole",
  "Credit Suisse",
  "DBS Bank",
  "Deutsche Bank",
  "Everbright Bank",
  "Fannie Mae",
  "Fidelity Investments",
  "Fifth Third Bank",
  "First Abu Dhabi Bank",
  "First Republic Bank",
  "Franklin Templeton",
  "Goldman Sachs",
  "Grupo Financiero Banorte",
  "Groupe BPCE",
  "Hang Seng Bank",
  "HDFC Bank",
  "HSBC",
  "ICBC",
  "ING Group",
  "Invesco",
  "Intesa Sanpaolo",
  "Itaú Unibanco",
  "JP Morgan Chase",
  "Julius Baer",
  "KB Financial Group",
  "KBC Bank",
  "LGT Bank",
  "Liberty Mutual",
  "Lloyds Banking Group",
  "Macquarie Group",
  "Marsh & McLennan",
  "Mastercard",
  "MetLife",
  "Mitsubishi UFJ Financial Group",
  "Mizuho Financial Group",
  "Morgan Stanley",
  "National Australia Bank",
  "Nationwide Building Society",
  "NatWest Group",
  "Nomura Holdings",
  "Nordea",
  "Northern Trust",
  "Oversea-Chinese Banking Corporation",
  "Ping An Insurance",
  "PNC Financial Services",
  "Postal Savings Bank of China",
  "Prudential Financial",
  "Qatar National Bank",
  "Rabobank",
  "Raymond James",
  "Regions Financial",
  "Rothschild & Co",
  "Royal Bank of Canada",
  "Scotiabank",
  "Shanghai Pudong Development Bank",
  "Shinhan Financial Group",
  "Société Générale",
  "Standard Chartered",
  "State Bank of India",
  "State Street",
  "Sumitomo Mitsui Financial Group",
  "Suncorp Group",
  "Svenska Handelsbanken",
  "TD Bank Group",
  "TD Securities",
  "Truist Financial",
  "UBS",
  "UniCredit",
  "US Bancorp",
  "Vanguard Group",
  "Visa",
  "Wells Fargo",
  "Westpac",
  "Zurich Insurance Group"
];

// Account types
export const ACCOUNT_TYPES = [
  "Cash",
  "Portfolio",
  "Investment",
  "Custody",
  "Broker",
  "Checking",
  "Savings",
  "Brokerage",
  "Trust",
  "Retirement",
  "Private Equity",
  "Hedge Fund",
  "Venture Capital",
  "Real Estate",
  "Fixed Income",
  "Credit",
  "Other"
];

// Currencies - Expanded list of global currencies with symbols
export const CURRENCIES = [
  "USD - US Dollar",
  "EUR - Euro",
  "GBP - British Pound",
  "CHF - Swiss Franc",
  "JPY - Japanese Yen",
  "CNY - Chinese Yuan",
  "CAD - Canadian Dollar",
  "AUD - Australian Dollar",
  "HKD - Hong Kong Dollar",
  "SGD - Singapore Dollar",
  "NZD - New Zealand Dollar",
  "SEK - Swedish Krona",
  "NOK - Norwegian Krone",
  "DKK - Danish Krone",
  "BRL - Brazilian Real",
  "INR - Indian Rupee",
  "MXN - Mexican Peso",
  "ZAR - South African Rand",
  "RUB - Russian Ruble",
  "TRY - Turkish Lira",
  "AED - UAE Dirham",
  "SAR - Saudi Riyal",
  "KRW - South Korean Won",
  "PLN - Polish Zloty",
  "THB - Thai Baht",
  "IDR - Indonesian Rupiah",
  "PHP - Philippine Peso",
  "MYR - Malaysian Ringgit",
  "CZK - Czech Koruna",
  "HUF - Hungarian Forint"
];

// Aggregators list
export const AGGREGATORS = [
  "Addepar",
  "Allvue",
  "Backstop Solutions",
  "Black Diamond",
  "Canoe Intelligence",
  "Clearwater Analytics",
  "Dynamo Software",
  "Eze Castle",
  "FactSet",
  "FIS",
  "FundCount",
  "Ledgex",
  "Masttro",
  "Mirador",
  "PCR",
  "Pitchbook",
  "SEI Archway",
  "Solovis",
  "SS&C Advent",
  "SS&C Geneva",
  "Tamarac",
  "Yardi",
  "Custom Solution",
  "Other"
];

// Countries - Comprehensive list of countries
export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", 
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", 
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", 
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", 
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", 
  "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", 
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", 
  "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", 
  "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", 
  "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", 
  "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", 
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", 
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", 
  "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", 
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", 
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", 
  "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", 
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", 
  "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", 
  "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

// Jurisdictions - Comprehensive list
export const JURISDICTIONS = [
  "Afghanistan", "Alabama (US)", "Alaska (US)", "Albania", "Alberta (Canada)", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
  "Arizona (US)", "Arkansas (US)", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
  "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
  "British Columbia (Canada)", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "California (US)", "Cambodia", "Cameroon", "Canada",
  "Cayman Islands", "Central African Republic", "Chad", "Channel Islands", "Chile", "China", "Colorado (US)", "Colombia", "Connecticut (US)", "Costa Rica",
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Delaware (US)", "Denmark", "District of Columbia (US)", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "England and Wales (UK)", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland",
  "Florida (US)", "France", "Gabon", "Gambia", "Georgia (Country)", "Georgia (US)", "Germany", "Ghana", "Gibraltar", "Greece",
  "Grenada", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Hawaii (US)", "Honduras", "Hong Kong", "Hungary",
  "Iceland", "Idaho (US)", "Illinois (US)", "India", "Indiana (US)", "Indonesia", "Iowa (US)", "Iran", "Iraq", "Ireland",
  "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kansas (US)", "Kazakhstan", "Kentucky (US)",
  "Kenya", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
  "Lithuania", "Louisiana (US)", "Luxembourg", "Macau", "Madagascar", "Maine (US)", "Malawi", "Malaysia", "Maldives", "Mali",
  "Malta", "Manitoba (Canada)", "Marshall Islands", "Maryland (US)", "Massachusetts (US)", "Mauritania", "Mauritius", "Mexico", "Michigan (US)", "Minnesota (US)",
  "Mississippi (US)", "Missouri (US)", "Moldova", "Monaco", "Mongolia", "Montana (US)", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nebraska (US)", "Nepal", "Netherlands", "Nevada (US)", "New Brunswick (Canada)", "New Hampshire (US)", "New Jersey (US)", "New Mexico (US)", "New York (US)",
  "New Zealand", "Newfoundland and Labrador (Canada)", "Nicaragua", "Niger", "Nigeria", "North Carolina (US)", "North Dakota (US)", "Northern Ireland (UK)", "Northwest Territories (Canada)", "Norway",
  "Nova Scotia (Canada)", "Nunavut (Canada)", "Ohio (US)", "Oklahoma (US)", "Oman", "Ontario (Canada)", "Oregon (US)", "Pakistan", "Panama", "Papua New Guinea",
  "Paraguay", "Pennsylvania (US)", "Peru", "Philippines", "Poland", "Portugal", "Prince Edward Island (Canada)", "Qatar", "Quebec (Canada)", "Rhode Island (US)",
  "Romania", "Russia", "Rwanda", "Saskatchewan (Canada)", "Saudi Arabia", "Scotland (UK)", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
  "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Carolina (US)", "South Dakota (US)", "South Korea", "Spain",
  "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Tennessee (US)",
  "Texas (US)", "Thailand", "Togo", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Utah (US)", "Uzbekistan", "Vatican City", "Venezuela", "Vermont (US)", "Vietnam", "Virginia (US)",
  "Washington (US)", "West Virginia (US)", "Wisconsin (US)", "Wyoming (US)", "Yemen", "Yukon Territory (Canada)", "Zambia", "Zimbabwe"
];
